### ISSUE TITLE
Gen 3 Device Support?

### ISSUE THREAD

**Issue by brooksben11** [eliteio/Arduino_New_Ping#3]
I understand that SparkIntervalTimer doesn't support Gen 3 devices yet due to OS limitations (at least that's my very limited understanding). Is there any way to fix/adjust this library in the meantime so that it doesn't use that or is that integral to it's functionality?

I've found this particular library to make working with ultrasonic sensors not only significantly easier, but that the outputs much more reliable (I seem to get a lot of errant readings otherwise). I'd love to be able to use it with my Gen 3 devices.

Thanks!

**Comment by ScruffR** [comment]
IIRC correctly this library heavily relies on precisely timed interrupts and consequently *revolves* around timed interrupts which are most practically facilitated via SparkIntervalTimer (where it works).

**Comment by brooksben11** [comment]
That's kind of what I figured. Any idea when/if they'll get support for SparkIntervalTimer for Gen 3 devices?

**Comment by ScruffR** [comment]
Nope, but with the additional info Rick has provided in his [repo](https://github.com/rickkas7/ADCDMAGen3_RK) things might start moving again.
